[versions]
kotlin = "1.9.24"
androidxCamera = "1.3.4"
composeBom = "2024.10.01"
mlkitFace = "16.1.6"
awsAndroid = "2.73.0"

[libraries]
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidxCamera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidxCamera" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

mlkit-face = { module = "com.google.mlkit:face-detection", version.ref = "mlkitFace" }

aws-core = { module = "com.amazonaws:aws-android-sdk-core", version.ref = "awsAndroid" }
aws-rekognition = { module = "com.amazonaws:aws-android-sdk-rekognition", version.ref = "awsAndroid" }
aws-cognito = { module = "com.amazonaws:aws-android-sdk-cognitoidentityprovider", version.ref = "awsAndroid" }
